name: vanilla-image-sac
device: ${oc.env:DEVICE,cuda:0}   # fallback to cuda:0


obs_keys: ['rgb']
reward_key: 'reward'

context_horizon: 1
each_image_shape: [3, 84, 84]

hidden_dim: 256
feature_dim: 512
action_dim: 12
action_range: 1.0

actor_lr: 3e-4
critic_lr: 3e-4
alpha_lr: 3e-4
tau: 0.005
gamma: 0.99
batch_size: 256

replay_capacity: 1000000 
initial_act_steps: 100
train_freq: 1
gradient_steps: 1
target_update_interval: 1

total_update_steps: 1000000
validation_interval: 10000
eval_checkpoint: -1

save_reply: False